gradle:
  image: gradle:alpine
  working_dir: /home/gradle/project
  command: "gradle clean run"
  volumes:
    - ./:/home/gradle/project
    - ~/.m2:/home/gradle/.m2
    - ~/.gradle:/home/gradle/.gradle
  ports:
    - "3000:3000"
    - "3001:3001"
    - "8000:8000"
  extra_hosts:
    - "localdev:192.168.56.102"
